/* =====================================================
   INVINCIBLE 360 — PRINCIPAL'S EYE UI
   Phase 3B

   Teacher/Admin only.
   Displays intervention signals generated by
   InvinciblePrincipalEye.

   Does not modify student mastery.
===================================================== */

(function (window, document) {
  'use strict';

  const GUARD =
    window.InvincibleRoleGuard;

  async function allowed() {
    if (!GUARD) {
      console.warn(
        '[Principal Eye UI] Role guard unavailable.'
      );
      return false;
    }

    return await GUARD.requireTeacher();
  }

  function createStyles() {

    if (
      document.getElementById(
        'principalEyeStyles'
      )
    ) {
      return;
    }

    const style =
      document.createElement('style');

    style.id =
      'principalEyeStyles';

    style.textContent = `
      #principalEyePanel {
        margin: 24px 0;
        padding: 22px;
        border-radius: 20px;
        background:
          linear-gradient(
            145deg,
            rgba(15,23,42,.98),
            rgba(5,8,17,.98)
          );
        border:
          1px solid rgba(0,229,255,.20);
        box-shadow:
          0 16px 45px rgba(0,0,0,.35);
      }

      .pe-header {
        display:flex;
        justify-content:space-between;
        align-items:center;
        gap:16px;
        margin-bottom:18px;
      }

      .pe-title {
        font-size:20px;
        font-weight:900;
        color:#fff;
      }

      .pe-subtitle {
        margin-top:4px;
        font-size:12px;
        color:#8793A8;
      }

      .pe-refresh {
        border:none;
        border-radius:10px;
        padding:9px 13px;
        background:#00D9FF;
        color:#001018;
        font-weight:900;
        cursor:pointer;
      }

      .pe-summary {
        display:grid;
        grid-template-columns:
          repeat(3,minmax(0,1fr));
        gap:10px;
        margin-bottom:18px;
      }

      .pe-stat {
        padding:14px;
        border-radius:14px;
        background:
          rgba(255,255,255,.035);
        border:
          1px solid rgba(255,255,255,.06);
      }

      .pe-stat-label {
        font-size:10px;
        color:#8793A8;
        text-transform:uppercase;
        letter-spacing:.7px;
        font-weight:800;
      }

      .pe-stat-value {
        margin-top:5px;
        font-size:24px;
        font-weight:900;
        color:#fff;
      }

      .pe-risk {
        border-radius:15px;
        padding:15px;
        margin-bottom:10px;
        background:
          rgba(255,255,255,.035);
        border:
          1px solid rgba(255,255,255,.06);
      }

      .pe-risk-high {
        border-color:
          rgba(255,61,110,.35);
      }

      .pe-risk-medium {
        border-color:
          rgba(255,176,0,.30);
      }

      .pe-risk-top {
        display:flex;
        justify-content:space-between;
        align-items:center;
        gap:10px;
      }

      .pe-student {
        font-weight:900;
        color:#fff;
        font-size:14px;
      }

      .pe-priority {
        font-size:9px;
        font-weight:900;
        padding:4px 7px;
        border-radius:7px;
        text-transform:uppercase;
      }

      .pe-high {
        color:#ff6b8b;
        background:
          rgba(255,61,110,.12);
      }

      .pe-medium {
        color:#ffc44d;
        background:
          rgba(255,176,0,.12);
      }

      .pe-meta {
        margin-top:7px;
        color:#A8B3C5;
        font-size:11px;
        line-height:1.5;
      }

      .pe-reason {
        margin-top:10px;
        padding:9px 10px;
        border-radius:10px;
        background:
          rgba(0,229,255,.05);
        color:#DDE7F5;
        font-size:11px;
        line-height:1.5;
      }

      .pe-action {
        margin-top:10px;
        font-size:10px;
        font-weight:900;
        color:#00D9FF;
        text-transform:uppercase;
        letter-spacing:.5px;
      }

      .pe-empty {
        padding:20px;
        text-align:center;
        color:#8793A8;
        font-size:12px;
        border-radius:14px;
        background:
          rgba(255,255,255,.025);
      }

      @media(max-width:640px) {
        .pe-summary {
          grid-template-columns:1fr;
        }

        .pe-header {
          align-items:flex-start;
        }
      }
    `;

    document.head.appendChild(style);
  }

  function escapeHTML(value) {

    const div =
      document.createElement('div');

    div.textContent =
      String(value ?? '');

    return div.innerHTML;
  }

  function buildPanel() {

    if (
      document.getElementById(
        'principalEyePanel'
      )
    ) {
      return document.getElementById(
        'principalEyePanel'
      );
    }

    const panel =
      document.createElement('section');

    panel.id =
      'principalEyePanel';

    panel.innerHTML = `
      <div class="pe-header">
        <div>
          <div class="pe-title">
            PRINCIPAL'S EYE
          </div>

          <div class="pe-subtitle">
            Learning-system intervention signals
          </div>
        </div>

        <button
          type="button"
          id="principalEyeRefresh"
          class="pe-refresh">
          Refresh
        </button>
      </div>

      <div
        id="principalEyeSummary"
        class="pe-summary">
      </div>

      <div
        id="principalEyeQueue">
      </div>
    `;

    /*
      Put the panel near the beginning of the
      teacher dashboard without replacing existing UI.
    */

    const main =
      document.querySelector('main');

    if (main) {
      main.prepend(panel);
    } else {
      document.body.prepend(panel);
    }

    return panel;
  }

  function render() {

    const engine =
      window.InvinciblePrincipalEye;

    if (!engine) {
      console.warn(
        '[Principal Eye UI] Engine unavailable.'
      );
      return;
    }

    const summary =
      engine.getSummary();

    const queue =
      engine.getInterventionQueue();

    const summaryEl =
      document.getElementById(
        'principalEyeSummary'
      );

    const queueEl =
      document.getElementById(
        'principalEyeQueue'
      );

    if (!summaryEl || !queueEl) {
      return;
    }

    summaryEl.innerHTML = `
      <div class="pe-stat">
        <div class="pe-stat-label">
          Students Affected
        </div>
        <div class="pe-stat-value">
          ${summary.studentsAffected}
        </div>
      </div>

      <div class="pe-stat">
        <div class="pe-stat-label">
          High Priority
        </div>
        <div class="pe-stat-value">
          ${summary.high}
        </div>
      </div>

      <div class="pe-stat">
        <div class="pe-stat-label">
          Risk Signals
        </div>
        <div class="pe-stat-value">
          ${summary.totalRiskSignals}
        </div>
      </div>
    `;

    if (!queue.length) {

      queueEl.innerHTML = `
        <div class="pe-empty">
          No intervention signals detected.
        </div>
      `;

      return;
    }

    queueEl.innerHTML =
      queue.map(
        function (item) {

          const priority =
            String(
              item.priority || 'LOW'
            ).toUpperCase();

          const priorityClass =
            priority === 'HIGH'
              ? 'pe-high'
              : 'pe-medium';

          const riskClass =
            priority === 'HIGH'
              ? 'pe-risk-high'
              : 'pe-risk-medium';

          return `
            <div
              class="pe-risk ${riskClass}">

              <div class="pe-risk-top">

                <div class="pe-student">
                  Student:
                  ${escapeHTML(
                    item.studentId
                  )}
                </div>

                <div
                  class="pe-priority ${priorityClass}">
                  ${escapeHTML(
                    priority
                  )}
                </div>

              </div>

              <div class="pe-meta">

                <strong>
                  Subject:
                </strong>
                ${escapeHTML(
                  item.subject
                )}

                ${
                  item.chapter
                    ? `
                      <br>
                      <strong>
                        Chapter:
                      </strong>
                      ${escapeHTML(
                        item.chapter
                      )}
                    `
                    : ''
                }

                <br>

                <strong>
                  Concept:
                </strong>
                ${escapeHTML(
                  item.concept
                )}

                ${
                  item.accuracy !== null &&
                  item.accuracy !== undefined
                    ? `
                      <br>
                      <strong>
                        Accuracy:
                      </strong>
                      ${Math.round(
                        Number(
                          item.accuracy
                        ) || 0
                      )}%
                    `
                    : ''
                }

              </div>

              <div class="pe-reason">
                ${escapeHTML(
                  item.reason
                )}
              </div>

              <div class="pe-action">
                ${escapeHTML(
                  item.recommendedAction
                )}
              </div>

            </div>
          `;
        }
      )
      .join('');
  }

  async function init() {

    const isAllowed =
      await allowed();

    if (!isAllowed) {
      return;
    }

    createStyles();

    buildPanel();

    const refresh =
      document.getElementById(
        'principalEyeRefresh'
      );

    if (refresh) {
      refresh.addEventListener(
        'click',
        render
      );
    }

    render();

    console.log(
      '[Principal Eye UI] Teacher dashboard ready.'
    );
  }

  window.InvinciblePrincipalEyeUI = {
    init,
    render,
    version: '3.0.0'
  };

  /*
    The teacher page may load some components
    asynchronously, so initialise shortly after
    the page becomes available.
  */

  if (
    document.readyState ===
    'loading'
  ) {

    document.addEventListener(
      'DOMContentLoaded',
      init
    );

  } else {
    init();
  }

})(window, document);